- added test for checking if etcd-disk is added to spec

diff --git a/e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml b/e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
--- a/e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
+++ b/e2e/capl-cluster-flavors/kubeadm-full-capl-cluster/chainsaw-test.yaml
@@ -13,7 +13,7 @@ spec:
   bindings:
     # Identifier for the E2E test run
     - name: run
-      value: (join('-', ['e2e', 'kdm-ft', env('GIT_REF')]))
+      value: (join('-', ['e2e', 'kdmf-tst', env('GIT_REF')]))
     - name: cluster
       # Format the cluster name
       value: (trim((truncate(($run), `32`)), '-'))
@@ -213,6 +213,56 @@ spec:
               KUBECONFIG=./kubeadm-full-cluster-kubeconfig.yaml kubectl logs csi-linode-controller-0 -n kube-system
             check:
               ($error == null): true
+
+    # Test to check if disks are added to the etcd spec
+    - clusters:
+        kubeadm-full-cluster:
+          kubeconfig: ./kubeadm-full-cluster-kubeconfig.yaml
+      name: Testing to check if disks are added to the spec
+      try:
+        - script:
+            env:
+              - name: TARGET_API
+                value: api.linode.com
+              - name:  TARGET_API_VERSION
+                value: v4beta
+              - name: URI
+                value: linode/instances
+              - name: FILTER
+                value: (to_string({"tags":($cluster)}))
+            content: |
+              set -e
+              
+              RESPONSE=$(curl -s \
+                -H "Authorization: Bearer $LINODE_TOKEN" \
+                -H "Content-Type: application/json" \
+                "https://$TARGET_API/$TARGET_API_VERSION/$URI")
+              
+              LINODE_ID=$(echo "$RESPONSE" | jq -r '.data[0].id')
+              
+              if [ -z "$LINODE_ID" ]; then
+                echo "Error: LINODE_ID is empty. Response was: $RESPONSE"
+                exit 1
+              fi
+
+              DISK_RESPONSE=$(curl -s \
+                -H "Authorization: Bearer $LINODE_TOKEN" \
+                -H "Content-Type: application/json" \
+                "https://$TARGET_API/$TARGET_API_VERSION/$URI/$LINODE_ID/disks?page=1&page_size=100")
+              
+              ETCD_LABEL=$(echo "$DISK_RESPONSE" | jq -r '.data[2].label')
+              ETCD_STATUS=$(echo "$DISK_RESPONSE" | jq -r '.data[2].status')
+              
+              echo "{
+                \"label\": \"$ETCD_LABEL\",
+                \"status\": \"$ETCD_STATUS\"
+              }"
+
+            check:
+              ($error): ~
+              (json_parse($stdout)):
+                label: etcd_disk
+                status: ready
 
     # Test to check if child cluster is deleted
     - name: Testing to see if child cluster is deleted
